# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
    Obrigado por abrir sua primeira edição! Certifique-se de seguir o modelo de problema e fornecer todas as informações para ajudar os desenvolvedores!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
    Obrigado por abrir esta solicitação pull! Confira nossas diretrizes de contribuição e certifique-se de seguir o modelo de pull request.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
    Parabéns por mesclar sua primeira solicitação pull! Continue fazendo grandes coisas conosco, obrigado!!

todo:
    keyword: '@todo'
